server:
  port: 8081
spring:
  datasource:
    password: rootpass
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysqldata:3306/event-service?createDatabaseIfNotExist=true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    consul:
      host: discovery
      port: 8500
management:
  endpoints:
    web:
      exposure:
        include: refresh
