server:
  port: 8091
spring:
  datasource:
    password: rootpass
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysqldata-event-service:3306/event-service?createDatabaseIfNotExist=true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  cloud:
    consul:
      host: discovery
      discovery:
        instanceId: ${spring.application.name}:${server.port}:${random.value}
        health-check-url: http://event-service:8091/actuator/health
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
management:
  endpoints:
    web:
      exposure:
        include: refresh,health
file:
  storage:
    location: /fileStorage
