server:
  port: 8081
spring:
  datasource:
    password: rootpass
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    uri: jdbc:mysql://localhost:3306/event-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      exposure:
        include: refresh
