server:
  port: 8080
spring:
  datasource:
    password: rootpass
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysqldata:3306/ticket-ordering-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: refresh
