server:
  port: 8090
spring:
  datasource:
    password: rootpass
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysqldata-ticket-ordering-service:3306/ticket-ordering-service?createDatabaseIfNotExist=true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  cloud:
    consul:
      host: discovery
      discovery:
        instanceId: ${spring.application.name}:${server.port}:${random.value}
        health-check-url: http://ticket-ordering-service:8090/actuator/health
management:
  endpoints:
    web:
      exposure:
        include: refresh,health
