spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/event/**
          filters:
            - RewritePath=/event/(?<path>.*), /$\{path}
        - id: ticket-ordering-service
          uri: lb://ticket-ordering-service
          predicates:
            - Path=/ticket-ordering/**
          filters:
            - RewritePath=/ticket-ordering/(?<path>.*), /$\{path}
            - TokenRelay=
    consul:
      host: discovery
      discovery:
        instanceId: ${spring.application.name}:${server.port}:${random.value}
        health-check-url: http://gateway-service:8072/actuator/health
management:
  endpoints:
    web:
      exposure:
        include: '*'
