server:
  port: 8072
spring:
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
            - GET
            - POST
            - OPTIONS
            - DELETE
            allowedHeaders: "*"
      routes:
        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/api/v1/events/**
          filters:
            - RewritePath=/api/v1/events/(?<path>.*), /api/v1/$\{path}
        - id: ticket-ordering-service
          uri: lb://ticket-ordering-service
          predicates:
            - Path=/ticket-ordering/**
          filters:
            - RewritePath=/ticket-ordering/(?<path>.*), /$\{path}
        - id: keycloak
          uri: ${KEYCLOAK_URI}
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<path>.*), /$\{path}
    consul:
      host: discovery
      discovery:
        instanceId: ${spring.application.name}:${server.port}:${random.value}
        health-check-url: http://gateway:8072/actuator/health
management:
  endpoints:
    web:
      exposure:
        include: '*'
